### ISSUE TITLE
Parallel letter counting - Rust 1.63 allows scoped threads

### ISSUE THREAD

**Issue by Redundancy** [exercism/rust#1575]
My understanding is that exercism currently doesn't use Rust 1.63+, but that the `std::thread::scope` would be a very standard (and ergonomic?) solution to the lifetime issues of the input reference in the parallel letter counting problem (https://github.com/exercism/rust/blob/main/exercises/practice/parallel-letter-frequency/src/lib.rs)

Is updating a big thing, or could it be considered?

**Comment by petertseng** [comment]
The Rust track uses whichever versions are the current stable, beta, and nightly versions. As of November 3, stable is 1.65.0 and beta is 1.66.0. It's hard to imagine what reasons would convince the track to change its policy on this front.

**Comment by petertseng** [comment]
EBWODP: But what is more important than what the track uses is what version the test runner uses, which can be found in https://github.com/exercism/rust-test-runner/blob/main/Dockerfile

**Comment by petertseng** [comment]
The Rust track uses whichever versions are the current stable, beta, and nightly versions. As of November 3, stable is 1.65.0 and beta is 1.66.0 so those are the versions the Rust track uses. It's hard to imagine what reasons would convince the track to change its policy on this front. For this reason, the Rust track is only able to include code that works on the current stable version, 1.65.0 as of this writing.

But, the version used by the test runner will govern what students are able to submit. This only applies to code that is placed in files distributed to students. The version used by the test runner can be found in https://github.com/exercism/rust-test-runner/blob/main/Dockerfile.

**Comment by Redundancy** [comment]
I'm a little confused then. According to this: https://blog.rust-lang.org/2022/08/11/Rust-1.63.0.html the scope::thread api was stabilized in 1.63, and I have been using it locally.

However, when I submit my solution, I get:
```
Compiling parallel-letter-frequency v0.0.0 (/mnt/exercism-iteration)
error[E0658]: use of unstable library feature 'scoped_threads'
  --> src/lib.rs:11:5
   |
11 |     thread::scope(|scope| {
   |     ^^^^^^^^^^^^^
   |
   = note: see issue #93203 <https://github.com/rust-lang/rust/issues/93203> for more information
   = help: add `#![feature(scoped_threads)]` to the crate attributes to enable
```

**Comment by petertseng** [comment]
Then the Rust test runner must not be using 1.63.0 (or later). That's a discussion to be had at https://github.com/exercism/rust-test-runner, then.

**Comment by Redundancy** [comment]
Closing in favour of https://github.com/exercism/rust-test-runner/issues/60
